# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073a212ae8274cd9ea7ccf007925c57ece0fd108f986ff8e323587245c076681fc90823d2db9d6b1ce988135fcd44ace1cb602a537433d98f4d93751b1846b87

test:
  secret_key_base: e5c2e20beea218f53541393ee5e7e4446aaa13da2c39d5e7daf5e078122e4da95db0c882478a6b02d7b75cc2d9e9448b8c159e3ab0530267d99a74fda286873d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
